apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-2
spec:
  type: NodePort
  ports:
    - port: 80 #where it listens inside the cluster
      targetPort: 80 #where it dispatches
      nodePort: 30000 #number between 30000 - 32767
  selector:
    app: first-pod
